# Generated by Django 2.2.6 on 2019-10-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20191005_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_multiple_choice',
            field=models.BooleanField(default=False),
        ),
    ]
